defmodule Tijara.Repo.Migrations.CreateJournalEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:journal_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :pair, :text, null: false
      add :type, :text, null: false
      add :entry_price, :decimal, null: false
      add :exit_price, :decimal
      add :size, :decimal, null: false, default: "1.0"
      add :strategy, :text
      add :notes, :text
      add :date, :date, null: false, default: fragment("CURRENT_DATE")
      add :status, :text, null: false, default: "open"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:journal_entries)
  end
end
